spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/z4movies-de

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka